data<-read.table("household_power_consumption.txt",header=T, na.strings = "?", sep=";",stringsAsFactors = F)
data2<-subset(data, data$Date=="1/2/2007"| data$Date=="2/2/2007")
idopont <- strptime(paste(data2$Date, data2$Time, sep=" "), "%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480)
plot(idopont,data2$Sub_metering_1,type="l",xlab="",ylab="Energy Submetering")
lines(idopont,data2$Sub_metering_2,col="red")
lines(idopont,data2$Sub_metering_3,col="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),col=c("black","red","blue"),lty=1)
dev.off()